version: "3"
services:
  web:
    image: tr007/hapi-mongo-server:1.0 # change build to image
    ports:
      - "3000:3000"

    volumes:
      - myremotevolume:/home/node/code
    links:
      - db
    # labels:
    #   kompose.service.type: LoadBalancer # need this label for Kubernetes
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017
  db:
    image: mongo:3
    ports:
      - "27017:27017" # explicitly expose the port

volumes:
  myremotevolume:
